spring.application.name=JobApp

spring.datasource.url=jdbc:mysql://localhost:3306/jobapp
spring.datasource.username=root
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect

# Use a secure 32+ char secret key (base64-safe)
jwt.secret=S7vBzFpX9Lc2hY@Xz#4mPkA0tH!zQpY*
